benchmark_name: lsbench_1.0
num_samples: null
image:
  width: 1024
  height: 1024
  batch_size: 4
  datasets:
    - axis-v1_1k
  vaes:
    - no_vae
    - name: flux_2
      path_to_model: models/FLUX.2-klein-4B/vae
  latent_storages:
    - fp32
    - fp16
    - bf16
    # 8-bit
    - fp8_e4m3
    - fp8_e5m2
    - fp8_e4m3_scaled
    - mxfp8
    - int8_tensor
    - int8_channel
    - int8_group
    - int8_asym
    - int8_mse_clip
    - int8_outlier
    - int8_hadamard
    - int8_mulaw
    - nf8
    # 4-bit
    - nvfp4
    - mxfp4
    - int4_group
    - int4_asym_group
    - {name: int4_asym_group, group_size: 4}
    - {name: int4_asym_group, group_size: 16}
    - {name: int4_asym_group, group_size: 64}
    - {name: int4_asym_square, block: 2}
    - {name: int4_asym_square, block: 4}
    - {name: int4_asym_square, block: 8}
    - int4_minmax_group
    - {name: int4_minmax_group, group_size: 4}
    - {name: int4_minmax_group, group_size: 16}
    - {name: int4_minmax_group, group_size: 64}
    - {name: int4_minmax_square, block: 2}
    - {name: int4_minmax_square, block: 4}
    - {name: int4_minmax_square, block: 8}
    - {name: int2_minmax_square, block: 2}
    - {name: int2_minmax_square, block: 4}
    - {name: int2_minmax_square, block: 8}
    - {name: int6_minmax_square, block: 2}
    - {name: int6_minmax_square, block: 4}
    - {name: int6_minmax_square, block: 8}
    - {name: int8_minmax_square, block: 2}
    - {name: int8_minmax_square, block: 4}
    - {name: int8_minmax_square, block: 8}
    - {name: lloyd_minmax_square, bits: 2, block: 4, range_bits: 5}
    - {name: lloyd_minmax_square, bits: 3, block: 4, range_bits: 5}
    - {name: lloyd_minmax_square, bits: 3, block: 8, range_bits: 6}
    - {name: lloyd_minmax_square, bits: 4, block: 4, range_bits: 5}
    - {name: lloyd_minmax_square, bits: 4, block: 8, range_bits: 6}
    - {name: lloyd_minmax_square, bits: 5, block: 4, range_bits: 5}
    - {name: lloyd_minmax_square, bits: 5, block: 8, range_bits: 6}
    - {name: lloyd_minmax_square, bits: 6, block: 8, range_bits: 6}
    - {name: lloyd_minmax_square, bits: 7, block: 8, range_bits: 6}
    - {name: lloyd_minmax_square, bits: 8, block: 8, range_bits: 6}
    - {name: normal_cdf_minmax_square, bits: 4, block: 4, range_bits: 5}
    - {name: normal_cdf_minmax_square, bits: 3, block: 4, range_bits: 5, std_scale: 2.5}
    - {name: normal_cdf_minmax_square, bits: 4, block: 4, range_bits: 5, std_scale: 2.5}
    - {name: normal_cdf_minmax_square, bits: 4, block: 8, range_bits: 6, std_scale: 2.5}
    - {name: normal_cdf_minmax_square, bits: 5, block: 4, range_bits: 5, std_scale: 2.5}
    - int4_mse_clip
    - int4_hadamard
    - int4_outlier
    - nf4
    - nf4_dq
    - kmeans4
  metrics:
    - mse
    - fid

video:
  datasets:
    - movirec
    - GasVideo1000
  vaes:
    - no_vae
  latent_storages:
    - fp32
    - fp16
    - bf16
  metrics:
    - mse
    - fid